# Generated by Django 5.2.12 on 2026-10-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='break_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_on_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='total_break_minutes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
